### ISSUE TITLE
CLI deletes custom fields when updating channel

### ISSUE THREAD

**Issue by SeniYG** [GetStream/stream-cli#37]
Hello,

I was trying to update a channel's image field via the CLI:

stream chat:channel:update -t 'messagingMembersOnly' -c "chatRoom_9nuDGTNQoEpF7NFzHhQ71U" --image=null

But that command had an unintended effect as it cleared most of the channel's other fields (like name, daisieRoomType, etc)

_**Feature request :**_
Is there a way to update custom fields (like daisieRoomType) using the CLI?

Additionally, is there a way to non-destructively update a field using the CLI?

**Comment by peterdeme** [comment]
This isn't applicable anymore
