### ISSUE TITLE
Translation support

### ISSUE THREAD

**Issue by tbarbugli** [GetStream/stream-cli#39]
Chat API now has support for [message translation](https://getstream.io/chat/docs/translation/?language=js) 🎉

Let's make sure the CLI simplify the configuration setup:

- enable/disable auto translate (application level)
- enable/disable auto translate (channel level)
- add an option to set the user language

**Comment by peterdeme** [comment]
https://github.com/GetStream/stream-cli/pull/110

**Comment by peterdeme** [comment]
Released https://github.com/GetStream/stream-cli/releases/tag/v1.1.0
