### ISSUE TITLE
unable to add custom data fields when creating a channel

### ISSUE THREAD

**Issue by mlaibow** [GetStream/stream-cli#40]
I always get a parsing error on trying to add a JSON string as custom data fields.

For example:
stream chat:channel:create -c=qsfm-general -d='{"vtag":"qsfm"}' -t=pxtype -n=#general

I have tried every format for the json string that i can think of.

Can you provide an example of a functional --data argument to chat:channel:create?

**Comment by tbarbugli** [comment]
Did you try escaping the double quotes? `-d "{\"vtag\": \"qsfm\"}"` If that does not work please include the full error here

**Comment by mlaibow** [comment]
It was in fact the escaping of the quotes. I have been using multiple computers with a variety of shells, and although i thought i tried the correct escape characters for each shell, it looks like i did not.
So for anyone else trying to do this, the single quote with double quote does not work on any shell.
The backslash escape \" works as above on bash and zsh.
For windows commands prompt it is a double double quotes:
-d="{""vtag"":""abstr""}"

But I could not get it to work for Windows Powershell using `, \, or "".

Thanks!

**Comment by peterdeme** [comment]
Released https://github.com/GetStream/stream-cli/releases/tag/v1.1.0
