### ISSUE TITLE
Error: timeout of falsems exceeded

### ISSUE THREAD

**Issue by dustfire** [GetStream/stream-cli#46]
Hey guys, just installed the CLI. Did the setup -- but I keep getting

```Error: timeout of falsems exceeded```

Any suggestions?

gz#6166

**Comment by rgkobashi** [comment]
I got the same error, you can just set some value instead of leaving the default. 20000 worked for me.

**Comment by dustfire** [comment]
Oh thanks @rgkobashi!! sorry for the dumb question but how do you do that :(

**Comment by rgkobashi** [comment]
I contacted support 😄

**Comment by dustfire** [comment]
Lol :) ok thanks

**Comment by ferhatelmas** [comment]
@rgkobashi thanks for helping. @dustfire #47 has the fix, should be released in a bit.

**Comment by dustfire** [comment]
Thanks guys ⚡️🙏
