### ISSUE TITLE
chat:message:list doesn't respect command line args

### ISSUE THREAD

**Issue by zbskii** [GetStream/stream-cli#53]
stream chat:message:list -c xyzzy is ignored and a captive interface still asks "What is the unique identifier for the channel?"

gz#8381

**Comment by shodgetts** [comment]
Agent comment from Ryan Kavanaugh in <a href='https://getstream.zendesk.com/agent/tickets/8381'>Zendesk ticket #8381</a>:<br><br>Hi,

Thanks for reaching out. We will look into this and get back to you as soon as possible. In the meantime, could you please provide your organization's name and AppId?

Best,
Ryan

**Comment by peterdeme** [comment]
This isn't applicable anymore with v1.0.0
