### ISSUE TITLE
Is there any kind of multi-config/multi-app support

### ISSUE THREAD

**Issue by uooq** [GetStream/stream-cli#54]
I'm trying to use this tool with a number of different stream apps. I've figured out that one can set the XDG_CONFIG_HOME env var to use different directories for the config file--  but before I dive deeper, I was curious if you've already built something in that allows config file overwriting? 

If not, I'll do some kind of wrapper script for the short-term and maybe submit a PR in the future with a better baked-in solution. 

gz#8486

**Comment by shodgetts** [comment]
Agent comment from Ryan Kavanaugh in <a href='https://getstream.zendesk.com/agent/tickets/8486'>Zendesk ticket #8486</a>:<br><br>Hi,

Thanks for getting in touch. We will look into this and get back to you shortly.

Best,
Ryan

**Comment by shodgetts** [comment]
Agent comment from Stephen Hodgetts in <a href='https://getstream.zendesk.com/agent/tickets/8486'>Zendesk ticket #8486</a>:<br><br>Hello, we have not built something like this to integrate a config file overwrite, sorry. We'll pass the request along to the engineers responsible for this tool though, it's a nice idea.

**Comment by wmadden** [comment]
It's really cumbersome to have to `stream config:set` every time you want to switch application

**Comment by peterdeme** [comment]
Supported in v1.0.0 ✅
