### ISSUE TITLE
Ability to supporrt multiple environments / configs

### ISSUE THREAD

**Issue by sukrit007** [GetStream/stream-cli#62]
In our use case, we have multiple environments, and to switch environments,  we need to rename file ~/.config/getstream-cli/config.json , and copy over file for the new environment.   

Is there a simpler way that this can be achieved? (Possibly a CLI option to pass config location or may be setting up different profiles like AWS CLI) ?

gz#10827

**Comment by peterdeme** [comment]
This is now supported in v1.0.0 ✅
