### ISSUE TITLE
Conflict with imagemagick

### ISSUE THREAD

**Issue by jamesholcomb** [GetStream/stream-cli#63]
I know this was already raised in https://github.com/GetStream/stream-cli/issues/33, but it is not a good recommendation for end users to just deal with imagemagick already being installed.

The rule of thumb in the global bin namespace is that if the name has been taken, find another one.  How about `streamio`...or anything really?  The burden of installing a program, then wondering why none of the config options work, then discovering oh, I have `stream` installed already?  I have no idea what that is...let's start searching on Google, etc etc.

gz#11106

**Comment by shodgetts** [comment]
Agent comment from Seetha in <a href='https://getstream.zendesk.com/agent/tickets/11106'>Zendesk ticket #11106</a>:<br><br>Hi

Thanks for reaching out to us.
We will check this and come back to you soon.

Cheers
Stream Team

**Comment by ferhatelmas** [comment]
@jamesholcomb thanks for the issue. Pushed a warning to install. However, no change in this binary because it's in maintenance mode and its complete rewrite will come where we will address it. Sorry for the inconvenience.
